from django.conf.urls import patterns, url

urlpatterns = patterns('',
   url('^login/$', 'django.contrib.auth.views.login',
       {'template_name': 'authentication/login.html'}, name='login'),
   url('^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
   url('^password_change/$', 'django.contrib.auth.views.password_change',
       {'post_change_redirect': '/', 'template_name': 'authentication/password_change.html'},
       name='password_change'),
   url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
       {'post_reset_redirect': 'authentication:password_reset_done',
        'template_name': 'authentication/password_reset_form.html',
        'email_template_name': 'authentication/password_reset_email.html'}, name='password_reset'),
   url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
       {'template_name': 'authentication/password_reset_done.html'}, name='password_reset_done'),
   url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       'django.contrib.auth.views.password_reset_confirm',
       {'template_name': 'authentication/password_reset_confirm.html',
        'post_reset_redirect': 'authentication:password_reset_complete'},
       name='password_reset_confirm'),
   url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
       {'template_name': 'authentication/password_reset_complete.html'}, name='password_reset_complete'),
   )